#! /bin/sh

## config
# maximum number of desktops to keep
MAX_DESKTOPS=9
# desktops per monitor
DESKTOPS_PER_MONITOR=3
# on which monitor to put remaining desktops (last/first)
REMAINING_DESKTOPS=last
# panel size
PANEL_SIZE=15
# file to run for setting up moniotrs
MONSETUP="$HOME/.config/bspwm/monitors_setup.sh"
[[ -f "$MONSETUP" ]] && . $MONSETUP && MONSETUP=true


### Configuration
: ${PANEL_SIZE:=14}
: ${MIN_DESKTOPS:=9}

bspc config top_padding $PANEL_SIZE
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config split_ratio         0.5
bspc config border_width        0
bspc config window_gap          0.1
bspc config borderless_monocle  false
bspc config gapless_monocle     false

### Desktops
### Make sure we always have $MIN_DESKTOPS desktops
bspc desktop -n desk1
BS_DESKTOPS=$(bspc query -D|wc -l)
if [[ $BS_DESKTOPS < $MIN_DESKTOPS ]]; then
    for ((i=$BS_DESKTOPS; i<=$MIN_DESKTOPS; i++)) {
        bspc monitor ^1 -a desk$i
    }
fi

## Monitor setup
[[ true == "$MONSETUP" ]] && monitors_setup

### RULES
# Global
bspc rule -a QuakeTermite sticky=on floating=on

# Desktop 1 - main1
# main terminal
bspc rule -a term-system desktop=^1 follow=off

# Desktop 2 - main2
# firefox
bspc rule -a Firefox desktop=^2 follow=on

# Desktop 3 - dev1
# dev (kapma) terminal
bspc rule -a term-dev-kapma desktop=^3 follow=off

# Desktop 4 - dev2

# Desktop 5 - media1
# gimp
bspc rule -a Gimp desktop=^5 floating=off follow=on
# steam
bspc rule -a Steam desktop=^5 floating=off follow=on

# Desktop 6 - games
# dota2
bspc rule -a dota_linux desktop=^6 floating=on follow=on

# Desktop 7 - system
# thunar
bspc rule -a Thunar desktop=^7 follow=on

# Desktop 8 - GTD

# Desktop 9 - media2

# Desktop 0 (10)
# keepass
bspc rule -a KeePass2 desktop=^9 follow=on


